# CMAKE generated file: DO NOT EDIT!
# Generated by "NMake Makefiles" Generator, CMake Version 3.9

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

!IF "$(OS)" == "Windows_NT"
NULL=
!ELSE
NULL=nul
!ENDIF
SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\JetBrains\CLion 2017.3.3\bin\cmake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\JetBrains\CLion 2017.3.3\bin\cmake\bin\cmake.exe" -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\Users\Rory\Documents\projects\cw_game

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\Users\Rory\Documents\projects\cw_game

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	echo >nul && "C:\Program Files\JetBrains\CLion 2017.3.3\bin\cmake\bin\cmake.exe" -E echo "No interactive CMake dialog available."
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache\fast: edit_cache

.PHONY : edit_cache\fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	echo >nul && "C:\Program Files\JetBrains\CLion 2017.3.3\bin\cmake\bin\cmake.exe" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache\fast: rebuild_cache

.PHONY : rebuild_cache\fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\Rory\Documents\projects\cw_game\CMakeFiles C:\Users\Rory\Documents\projects\cw_game\CMakeFiles\progress.marks
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\Rory\Documents\projects\cw_game\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) clean
.PHONY : clean

# The main clean target
clean\fast: clean

.PHONY : clean\fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall\fast:
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) preinstall
.PHONY : preinstall\fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cw

# Build rule for target.
cw: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) cw
.PHONY : cw

# fast build rule for target.
cw\fast:
	$(MAKE) -f CMakeFiles\cw.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\cw.dir\build
.PHONY : cw\fast

graphics\renderer.obj: graphics\renderer.cpp.obj

.PHONY : graphics\renderer.obj

# target to build an object file
graphics\renderer.cpp.obj:
	$(MAKE) -f CMakeFiles\cw.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\cw.dir\graphics\renderer.cpp.obj
.PHONY : graphics\renderer.cpp.obj

graphics\renderer.i: graphics\renderer.cpp.i

.PHONY : graphics\renderer.i

# target to preprocess a source file
graphics\renderer.cpp.i:
	$(MAKE) -f CMakeFiles\cw.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\cw.dir\graphics\renderer.cpp.i
.PHONY : graphics\renderer.cpp.i

graphics\renderer.s: graphics\renderer.cpp.s

.PHONY : graphics\renderer.s

# target to generate assembly for a file
graphics\renderer.cpp.s:
	$(MAKE) -f CMakeFiles\cw.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\cw.dir\graphics\renderer.cpp.s
.PHONY : graphics\renderer.cpp.s

graphics\window.obj: graphics\window.cpp.obj

.PHONY : graphics\window.obj

# target to build an object file
graphics\window.cpp.obj:
	$(MAKE) -f CMakeFiles\cw.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\cw.dir\graphics\window.cpp.obj
.PHONY : graphics\window.cpp.obj

graphics\window.i: graphics\window.cpp.i

.PHONY : graphics\window.i

# target to preprocess a source file
graphics\window.cpp.i:
	$(MAKE) -f CMakeFiles\cw.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\cw.dir\graphics\window.cpp.i
.PHONY : graphics\window.cpp.i

graphics\window.s: graphics\window.cpp.s

.PHONY : graphics\window.s

# target to generate assembly for a file
graphics\window.cpp.s:
	$(MAKE) -f CMakeFiles\cw.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\cw.dir\graphics\window.cpp.s
.PHONY : graphics\window.cpp.s

logger.obj: logger.cpp.obj

.PHONY : logger.obj

# target to build an object file
logger.cpp.obj:
	$(MAKE) -f CMakeFiles\cw.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\cw.dir\logger.cpp.obj
.PHONY : logger.cpp.obj

logger.i: logger.cpp.i

.PHONY : logger.i

# target to preprocess a source file
logger.cpp.i:
	$(MAKE) -f CMakeFiles\cw.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\cw.dir\logger.cpp.i
.PHONY : logger.cpp.i

logger.s: logger.cpp.s

.PHONY : logger.s

# target to generate assembly for a file
logger.cpp.s:
	$(MAKE) -f CMakeFiles\cw.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\cw.dir\logger.cpp.s
.PHONY : logger.cpp.s

logic\logic.obj: logic\logic.cpp.obj

.PHONY : logic\logic.obj

# target to build an object file
logic\logic.cpp.obj:
	$(MAKE) -f CMakeFiles\cw.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\cw.dir\logic\logic.cpp.obj
.PHONY : logic\logic.cpp.obj

logic\logic.i: logic\logic.cpp.i

.PHONY : logic\logic.i

# target to preprocess a source file
logic\logic.cpp.i:
	$(MAKE) -f CMakeFiles\cw.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\cw.dir\logic\logic.cpp.i
.PHONY : logic\logic.cpp.i

logic\logic.s: logic\logic.cpp.s

.PHONY : logic\logic.s

# target to generate assembly for a file
logic\logic.cpp.s:
	$(MAKE) -f CMakeFiles\cw.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\cw.dir\logic\logic.cpp.s
.PHONY : logic\logic.cpp.s

main.obj: main.cpp.obj

.PHONY : main.obj

# target to build an object file
main.cpp.obj:
	$(MAKE) -f CMakeFiles\cw.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\cw.dir\main.cpp.obj
.PHONY : main.cpp.obj

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles\cw.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\cw.dir\main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles\cw.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\cw.dir\main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... cw
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... graphics/renderer.obj
	@echo ... graphics/renderer.i
	@echo ... graphics/renderer.s
	@echo ... graphics/window.obj
	@echo ... graphics/window.i
	@echo ... graphics/window.s
	@echo ... logger.obj
	@echo ... logger.i
	@echo ... logger.s
	@echo ... logic/logic.obj
	@echo ... logic/logic.i
	@echo ... logic/logic.s
	@echo ... main.obj
	@echo ... main.i
	@echo ... main.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

